%YAML:1.0
#--------------------------------------------------------------------------------------------
# Feature Parameters
#--------------------------------------------------------------------------------------------

ORB:
    Extractor:
        N_Features: 1000
        scale_factor: 1.2
        N_Levels: 8
        N_Cells: 30
        threshold_init: 20
        threshold_min : 4
    
    Matcher:
        threshold_high: 100.0
        threshold_low: 50.0
        
    Vocabulary: ../config/Vocabulary/ORBvoc.bin
        
SURF:
    Extractor:
        N_Features: 1000
        N_Levels: 5
        N_Cells: 2
        threshold_init: 600
        threshold_min : 400
    
    Matcher:
        threshold_high: 1.5
        threshold_low: 0.75
        
    Vocabulary: ../config/Vocabulary/small_surf_voc.yml.gz
    

